/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xk_ndkdemo_Wathcer */

#ifndef _Included_com_xk_ndkdemo_Wathcer
#define _Included_com_xk_ndkdemo_Wathcer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xk_ndkdemo_Wathcer
 * Method:    startDaemon
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xk_ndkdemo_Wathcer_startDaemon
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
