/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xk_ndkdemo_MyNdk */

#ifndef _Included_com_xk_ndkdemo_MyNdk
#define _Included_com_xk_ndkdemo_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xk_ndkdemo_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xk_ndkdemo_MyNdk_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
